### ISSUE TITLE
serialRead problem

### ISSUE THREAD

**Issue by gostouche** [HirdayGupta/Java-Arduino-Communication-Library#11]
Hi, 
I'm having problems with reading a string sent from my arduino.
Arduino sends a string : "Batch is not schedulable\n", with Serial.println() and Serial.flush() after.
In my Java application when i wrote arduino.serialRead(1) it returned : 
Batch
 is

I read your source code but i can't understand what's the problem.
I tried with a lot of numbers and never got anything back.
Hope you can help.

Thanks for the library btw.  :)

**Comment by HirdayGupta** [comment]
@Gostuski thanks for your question, glad you're enjoying the library! If you take a look at the [wiki](https://github.com/HirdayGupta/Java-Arduino-Communication-Library/wiki/Instructions.), you'll see that `arduino.serialRead(int limit)` will read AT MOST `limit` number of characters. 

It's a little strange that its reading the full words "Batch is" but my recommendation would be to first try increasing the `limit` to the number of characters in that string (25). 

Lemme know if that doesn't work for this particular case! In the long run however, you should set up a packet-style communication with a definite packet length.

**Comment by gostouche** [comment]
Thank you for responding. I managed to fix the problem. Thanks again.
