### ISSUE TITLE
SerialPort using

### ISSUE THREAD

**Issue by AlmamyAZ** [HirdayGupta/Java-Arduino-Communication-Library#4]
Hello guys , I try to use the JSerialComm lib , on my project , but i have this following error 
![image](https://user-images.githubusercontent.com/37594122/38058514-717412d0-32e3-11e8-957d-8b7fbc83a44a.png)

Can someone help me ? 

Thanks

**Comment by HirdayGupta** [comment]
Hi @AlmamyAZ,

Did you follow step 1 on the [instructions page](https://github.com/HirdayGupta/Java-Arduino-Communication-Library/wiki/Instructions)? 

You need to add the jSerialComm.jar and arduino.jar as external jars to your buildpath. The instructions page contains a link to [this youtube video](https://www.youtube.com/watch?v=UtzAf8tyuAM) that shows you how to do this in eclipse.

**Comment by HirdayGupta** [comment]
Also, @AlmamyAZ,

Check out this [example code](https://github.com/HirdayGupta/Java-Arduino-Communication-Library/blob/master/src/examples/BasicLEDExample.java#L5) from the repo. If you're interested in using the `arduino` library, you don't need to manually import the `jSerialComm` package, just `import arduino.*;` and it should work (because the arduino package itself imports the parts of jSerialComm it needs)

**Comment by AlmamyAZ** [comment]
Thanks for your answer , I will try these tips. I am working on Netbeans , i suppose it is the same way ?


Almamy A KANTE Responsable projetsPolytech Services NancyEtudiant Ingénieur 4 A Polytech Nancy Master 1 EEATEL: 0753905196 

    Le jeudi 29 mars 2018 à 07:52:55 UTC+2, Hirday Gupta <notifications@github.com> a écrit :  
 
 
Also, @AlmamyAZ,

Check out this example code from the repo. If you're interested in using the arduino library, you don't need to manually import the jSerialComm package, just import arduino.*; and it should work for you.

**Comment by HirdayGupta** [comment]
Hi @AlmamyAZ, did the solution end up working? I’d be happy to help with follow up questions.

**Comment by AlmamyAZ** [comment]
Yes It worked ! Thank you for all your good job 
Almamy A KANTE Responsable projetsPolytech Services NancyEtudiant Ingénieur 4 A Polytech Nancy Master 1 EEATEL: 0753905196 

    Le lundi 6 août 2018 à 19:21:39 UTC+2, Hirday Gupta <notifications@github.com> a écrit :  
 
 
Hi @AlmamyAZ, did the solution end up working? I’d be happy to help with follow up questions.
