### ISSUE TITLE
How to use serialRead()

### ISSUE THREAD

**Issue by PilotinControl25** [HirdayGupta/Java-Arduino-Communication-Library#6]
Hello,

How do I invoke serialRead(); in my program? I am trying the following Java code and it does not work or I am not doing it correctly. serialWrite() works just fine. Thanks!
``` java
String line = arduino.serialRead();
if(line.equals("ON")){
    System.out.println("ON!!");
}
```

**Comment by HirdayGupta** [comment]
Hey @PilotinControl25,

Thanks for asking!

As I mentioned in the [Instructions Wiki](
https://github.com/HirdayGupta/Java-Arduino-Communication-Library/wiki/Instructions) (in Point 5-vii), depending on how you’ve set up your serial communication, the call to the method `serialRead()` could potentially result in an infinite loop. (As a result of which it may seem like your code isn’t working)

You might want to change your implementation to use the `serialRead(int limit)` function, which will limit the number of characters being read in and will definitely not result in an infinite loop. 

Let me know if you have further questions!

**Comment by PilotinControl25** [comment]
I took your advice and switching to `serialRead(int limit);` did the trick and works perfectly. Thanks!
